### ISSUE TITLE
Remove download button from emberjs integration

### ISSUE THREAD

**Issue by jasonmit** [yahoo/formatjs-site#168]
The download button on emberjs integration doesn't apply to `ember-intl`.  You would never, in normal circumstances, download the static assets since the addons should be installed using `ember install:addon ember-intl` or `npm install --save ember-intl`

I'd prefer we just target ember-cli with the exception of the custom packaging reserved mainly for this site.

Thoughts @ericf

**Comment by ericf** [comment]
Yeah makes sense.
