### ISSUE TITLE
French sentence is wrong

### ISSUE THREAD

**Issue by noopole** [yahoo/formatjs-site#193]
On the French homepage:
Wrong: "Le ‎15‎ ‎avril‎ ‎2015, Annie n'a pas pris de photographi<b>es</b>"
Shoud be: "Le ‎15‎ ‎avril‎ ‎2015, Annie n'a pas pris de photographi<b>e</b>"

**Comment by jlecomte** [comment]
I double-checked with my French grammar expert, aka my mom, and that is correct. Will fix in the near future.
