### ISSUE TITLE
Remove ember-intl docs from formatjs-site

### ISSUE THREAD

**Issue by jasonmit** [yahoo/formatjs-site#201]
As I move towards pushing 2.0 out, it is easier for me to no longer maintain the documentation due to the complexity of hosting an ember-cli addon within a react application.  I'd prefer to instead provide a link to the github wiki articles.

**Comment by ericf** [comment]
What's the new URL so I can point to the new docs site?

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/wiki

I'll continue to improve the docs over the weekend.
