### ISSUE TITLE
Add Polymer to list of FormatJS integrations

### ISSUE THREAD

**Issue by stramel** [yahoo/formatjs-site#209]
Polymer has a way to integrate formatjs into Polymer applications. Might be good to provide this information in the list of integrations?

https://elements.polymer-project.org/elements/app-localize-behavior

https://www.polymer-project.org/1.0/toolbox/localize

**Comment by ericf** [comment]
Yeah, sure. Feel free to send a PR if you have time.

**Comment by stramel** [comment]
@ericf Sorry for the late PR.

**Comment by stramel** [comment]
Resolved in #216
