### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by fabricetheytaz** [yahoo/formatjs-site#213]
Sorry for my bad english,
Dust v1.1.1 download link not working: https://github.com/yahoo/dust-intl/releases/download/v1.1.1/dust-intl-1.1.1.tgz may be https://github.com/yahoo/dust-intl/archive/v1.1.1.tar.gz ?

**Comment by redonkulus** [comment]
@fabricetheytaz this is fixed now https://formatjs.io/dust/
