### ISSUE TITLE
Example translations pile up when change locale

### ISSUE THREAD

**Issue by oluckyman** [yahoo/formatjs-site#215]
Go to https://formatjs.io/
Change Locale in dropdown to another. Then again and again. Go on. Sometimes previous translation remains and example div shows all of them:

![image](https://user-images.githubusercontent.com/642673/27571175-19b290ce-5b04-11e7-828b-4608b8f602f1.png)

**Comment by okuryu** [comment]
I cann't reproduce it. What browser are you using?

**Comment by oluckyman** [comment]
Google Chrome on Mac Version 59.0.3071.115 (Official Build) (64-bit)
Just tried again, cannot reproduce too.
I don’t remember for sure but seems like that time there was no transition animation on locale change.
